@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDIwNTY3ODh9.VIOBX4lquZKsIO3UAWphYvxY4oFtyAs7325-6LGQ8Mk

POST http://localhost:8080/login
###

GET http://localhost:8080/books
Authorization: Bearer {{token}}
###

POST http://localhost:8080/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "1",
  "title": "The Godfather",
  "author": "John Lark"
}
###

DELETE http://localhost:8080/books/1
Authorization: Bearer {{token}}
###
