GET http://localhost:8080/books
Authorization: Bearer ACCESS_TOKEN
###

POST http://localhost:8080/books
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN

{
  "id": "1",
  "title": "The Godfather",
  "author": "John Lark"
}
###

DELETE http://localhost:8080/books/1
Authorization: Bearer ACCESS_TOKEN
###

POST http://localhost:8080/login
